### ISSUE TITLE
Confirming module settings

### ISSUE THREAD

**Issue by CrypticaScriptura** [seigneur/lamassu-itbit#1]
Hi @seigneur, wanted to confirm how the module's settings mapped to recently obtained test credentials.

I received:
- User Name (in the form of a business name)
- User Email
- User ID (in the form of 286510VB-73D0-4C30-A6D9-64B2A4956B14)
- API Client
- API Secret

Am I correct in assuming `walletID` is the User ID, and `clientId` is the User Name? Thanks in advance.

**Comment by seigneur** [comment]
Hi @naconner,

The client ID is the user ID and the wallet ID is a particular wallet within your Itbit account. They have this concept of having multiple wallets within the same account. It is something like "axxxxxxx-7xx-xxx8-6xxa-xxxxxxxxxxx0", all lowercase.  :-)

Thanks

**Comment by CrypticaScriptura** [comment]
Thank you, @seigneur !
